
// 匯入soild圖示（可依需求增減）
import {
  faUtensils,
  faStar,
  faStarHalf,
  faStarHalfStroke,
  faMapMarkerAlt,
  faMobileAlt,
  faChevronLeft,
  faChevronRight,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faAddressCard,
  faGear,
  faArrowRightFromBracket,
  faXmark,
  faTableList,
  faBook,
  faPlus,
  faGaugeHigh,
  faInfoCircle,
  faBolt,
  faClock,
  faTriangleExclamation,
  faCrown,
  faMedal,
  faMinus,
  faStore
} from '@fortawesome/free-solid-svg-icons';

export const solidIcons = [
  faUtensils,
  faStar,
  faStarHalf,
  faStarHalfStroke,
  faMapMarkerAlt,
  faMobileAlt,
  faChevronLeft,
  faChevronRight,
  faSearch,
  faAngleLeft,
  faAngleRight,
  faMagnifyingGlassPlus,
  faMagnifyingGlassMinus,
  faAddressCard,
  faGear,
  faArrowRightFromBracket,
  faXmark,
  faTableList,
  faBook,
  faPlus,
  faGaugeHigh,
  faInfoCircle,
  faBolt,
  faClock,
  faTriangleExclamation, 
  faCrown,
  faMedal,
  faMinus,
  faStore
];